module.exports.config = { name: "approve", version: "1.0.2", hasPermssion: 2, credits: "Rasel Mahmud", description: "approve the gc using bots xD", commandCategory: "Admin", cooldowns: 5 };

const dataPath = __dirname + "/Priyanshu/approvedThreads.json"; const dataPending = __dirname + "/Priyanshu/pendingdThreads.json"; const fs = require("fs"); const axios = require("axios"); const request = require("request");

module.exports.onLoad = () => { if (!fs.existsSync(dataPath)) fs.writeFileSync(dataPath, JSON.stringify([])); if (!fs.existsSync(dataPending)) fs.writeFileSync(dataPending, JSON.stringify([])); };

module.exports.handleReply = async function ({ event, api, handleReply, args }) { if (handleReply.author != event.senderID) return; const { body, threadID, messageID } = event; const { type } = handleReply; let data = JSON.parse(fs.readFileSync(dataPath)); let dataP = JSON.parse(fs.readFileSync(dataPending)); let idBox = (args[0]) ? args[0] : threadID;

switch (type) { 	case "pending": { 		switch (body) { 			case `A`: { 				data.push(idBox); 				fs.writeFileSync(dataPath, JSON.stringify(data, null, 2)); 				api.sendMessage(`» Successfully approved the box:\n${idBox}`, threadID, () => { 					dataP.splice(dataP.indexOf(idBox), 1); 					fs.writeFileSync(dataPending, JSON.stringify(dataP, null, 2)); 				}, messageID); 			} 		} 	} } 

};

module.exports.run = async ({ event, api, args, Threads, Users }) => { const { threadID, messageID, senderID } = event; let data = JSON.parse(fs.readFileSync(dataPath)); let dataP = JSON.parse(fs.readFileSync(dataPending)); let msg = ""; var lydo = args.splice(2).join(" "); let idBox = (args[0]) ? args[0] : threadID;

if (args[0] == "list" || args[0] == "l") { 	msg = `=====「 GC THAT HAD BEEN APPROVED: ${data.length} 」 ====`; 	let count = 0; 	for (const e of data) { 		let threadInfo = await api.getThreadInfo(e); 		let threadName = threadInfo.threadName ? threadInfo.threadName : await Users.getNameUser(e); 		msg += `\n〘${++count}〙» ${threadName}\n${e}`; 	} 	api.sendMessage(msg, threadID, (error, info) => { 		global.client.handleReply.push({ 			name: this.config.name, 			messageID: info.messageID, 			author: event.senderID, 			type: "a", 		}); 	}, messageID); } else if (args[0] == "pending" || args[0] == "p") { 	msg = `=====「 THREADS NEED TO BE APPROVE: ${dataP.length} 」 ====`; 	let count = 0; 	for (const e of dataP) { 		let threadInfo = await api.getThreadInfo(e); 		let threadName = threadInfo.threadName ? threadInfo.threadName : await Users.getNameUser(e); 		msg += `\n〘${++count}〙» ${threadName}\n${e}`; 	} 	api.sendMessage(msg, threadID, (error, info) => { 		global.client.handleReply.push({ 			name: this.config.name, 			messageID: info.messageID, 			author: event.senderID, 			type: "pending", 		}); 	}, messageID); } else if (args[0] == "help" || args[0] == "h") { 	const tst = (await Threads.getData(String(event.threadID))).data || {}; 	const pb = (tst.hasOwnProperty("PREFIX")) ? tst.PREFIX : global.config.PREFIX; 	const nmdl = this.config.name; 	const cre = this.config.credits; 	return api.sendMessage(`=====「 APPROVE 」===== 

${pb}${nmdl} l/list => see list of approved boxes

${pb}${nmdl} p/pending => see the list of unapproved boxes

${pb}${nmdl} d/del => with ID to remove from bot used list

${pb}${nmdl} => Attach an ID to browse that box

⇒ ${cre} ⇐, threadID, messageID); } else if (args[0] == "del" || args[0] == "d") { idBox = (args[1]) ? args[1] : event.threadID; if (isNaN(parseInt(idBox))) return api.sendMessage("[ ERR ] Not a number", threadID, messageID); if (!data.includes(idBox)) return api.sendMessage("[ ERR ] Box is not pre-approved!", threadID, messageID); api.sendMessage([ OK ] Your group has been removed from the browsing list by the admin for the reason: ${lydo}, idBox); api.sendMessage([ OK ] Box has been removed from the list of allowed bots, threadID, () => { data.splice(data.indexOf(idBox), 1); fs.writeFileSync(dataPath, JSON.stringify(data, null, 2)); }, messageID); } else if (isNaN(parseInt(idBox))) { api.sendMessage("[ ERR ] The ID you entered is not valid", threadID, messageID); } else if (data.includes(idBox)) { api.sendMessage([ - ] ID ${idBox} pre-approved!`, threadID, messageID); } else { api.sendMessage("[ OK ] ✨আপনার গ্রুপটি এখন অনুমোদিত হয়েছে! ✨", idBox, async (error) => { if (error) return api.sendMessage("[ ERR ] Something went wrong, make sure the id you entered is valid and the bot is in the box!", threadID, messageID); else { data.push(idBox); fs.writeFileSync(dataPath, JSON.stringify(data, null, 2)); dataP.splice(dataP.indexOf(idBox), 1); fs.writeFileSync(dataPending, JSON.stringify(dataP, null, 2));

			axios.get('https://anime.apibypriyansh.repl.co/img/anime').then(res => { 				let ext = res.data.url.substring(res.data.url.lastIndexOf(".") + 1); 				let callback = function () { 					let link = ["https://www.facebook.com/iiii.482394"]; 					api.sendMessage({ 						body: `❒❒ BOT ARE NOW CONNECTED ❒❒\n=====================\n┏━━━━ 🖤 ━━━━┓\n ✦❥⋆⃝𝐑𝐀𝐒𝐄𝐋 ✦ \n┗━━━ 🖤 ━━━━┛\n=====================\n➪ BOT: ✨𝐌𝐀𝐆𝐈𝐂🔹𝐎𝐅🔸𝐒𝐎𝐔𝐍𝐃✨᯾\n➪ Prefix: ${global.config.PREFIX}\n➪ Users: ${global.data.allUserID.length}\n➪ Groups: ${global.data.allThreadID.length}\n=====================\n[]---------------------------------------[]\nUse '${global.config.PREFIX}help' to view the commands that are available!\n[]---------------------------------------[]\n⌨ Made by: Rasel Mahmud\n(${link[0]})`, 						attachment: fs.createReadStream(__dirname + `/cache/duyet.${ext}`) 					}, idBox, () => fs.unlinkSync(__dirname + `/cache/duyet.${ext}`)); 				}; 				request(res.data.url).pipe(fs.createWriteStream(__dirname + `/cache/duyet.${ext}`)).on("close", callback); 			}); 		} 	}); } 

};
